name: Pre-Compile and Lint

on:
  - push
  - pull_request

jobs:
  main:
    name: Main

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Cache Node Module Dependencies
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: nodemodules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
